POST http://localhost/member/register
Content-Type: application/json

{
  "mobile": "456132"
}

###
POST http://localhost/member/send-code
Content-Type: application/json

{
  "mobile": "15116778296"
}

###
