POST http://localhost/member/register
Content-Type: application/json

{
  "mobile": "456132"
}

###
POST http://localhost/member/send-code
Content-Type: application/json

{
  "mobile": "13027378933"
}

###
POST http://localhost/member/login
Content-Type: application/json

{
  "mobile": "13027378933",
  "code" : "8888"
}

> {%
 client.global.set("token",response.body.content.token);
 %}


###
POST http://localhost:8001/member/hello
Accept: application/json

###

GET http://localhost:8002/business/trainStation/admin/query-list
Accept: application/json

###
GET http://localhost:8002/business/dailyTrainTicket/admin/query-list?end=沈阳&currentPage=1&pageSize=2
Accept: application/json

###
