POST http://localhost/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id" : "1705555827190009856",
  "memberId" : 13213,
  "name" : "liuxiaolong",
  "idCard" : "430902200402020593",
  "type" : "1"
}

###
GET http://localhost/member/passenger/query-list?currentPage=1&pageSize=3
Accept: application/json
token: {{token}}


###

GET http://localhost/member/get-enum/Passenger
token: {{token}}
Accept: application/json

###

