server:
  port: 80
spring:
  application:
    name: batch
  cloud:
    gateway:
      routes: #配置路由转发
        - uri: http://127.0.0.1:8001
          id: member
          predicates:
            - Path=/member/**
        - uri: http://127.0.0.1:8002
          id: business
          predicates:
            - Path=/business/**
        - uri: http://127.0.0.1:8003
          id: batch
          predicates:
            - Path=/batch/**
request:
  whiteList:
    - /member/login
    - /member/send-code
    - /business/get-enum/**
    - /batch/**
