server:
  port: 80
spring:
  cloud:
    gateway:
      routes: #配置路由转发
        - uri: lb://member
          id: member
          predicates:
            - Path=/member/**
        - uri: lb://business
          id: business
          predicates:
            - Path=/business/**
        - uri: lb://batch
          id: batch
          predicates:
            - Path=/batch/**
request:
  whiteList:
    - /member/login
    - /member/send-code
    - /business/get-enum/**
    - /batch/**
