spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wiki?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: "wiki"
    password: "040202"
    driverClassName: com.mysql.cj.jdbc.Driver


server:
  port: 8002
  servlet:
    context-path: /business


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true #开启驼峰下划线转换
    cacheEnabled: true #开启二级缓存
    lazy-loading-enabled: true #开启懒加载
    aggressive-lazy-loading: false #关闭按需加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台打印sql

