spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/train_business?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: "root"
    password: "040202"
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: business
  data:
    redis:
      database: 0
      host: 39.107.52.125
      port: 6379
      password: "040202"
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_code_
      cache-null-values:  false
      time-to-live: 60s

server:
  port: 8002
  servlet:
    context-path: /business


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true #开启驼峰下划线转换
    lazy-loading-enabled: true #开启懒加载
    aggressive-lazy-loading: false #关闭按需加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台打印sql
    localCacheScope: statement #取消一级缓存，在有多个会话一级分布式场景会产生脏读现象

