spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/train_business?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: "root"
    password: "040202"
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: business
  data:
    redis:
      database: 0
      host: 39.107.52.125
      port: 6379
      password: "040202"
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_code_
      cache-null-values:  true #spring-boot-cache会自动帮我处理缓存穿透的问题
      time-to-live: 60s
  cloud:
    sentinel:  #sentinel使用nacos存储配置
      datasource:
        flow:
          nacos:
            serverAddr: 127.0.0.1:8848
            namespace: trainNameSpaceId
            groupId: TRAIN_GROUP
            dataId: sentinel
            ruleType: flow

#spring:
#  cloud:
#    sentinel:
#      # nacos 持久化数据
#      datasource:
#        # 可配置多个规则
#        # 可自定义key-流控规则
#        dashboard-flow:
#          nacos:
#            server-addr: http:localhost
#            dataId: ${spring.application.name}-flow
#            file-extension: json
#            rule-type: flow
#            namespace: ${spring.profiles.active}
#        # 可自定义key-系统规则
#        dashboard-system:
#          nacos:
#            server-addr: http:localhost
#            dataId: ${spring.application.name}-system
#            file-extension: json
#            rule-type: system
#            namespace: ${spring.profiles.active}

server:
  port: 8002
  servlet:
    context-path: /business




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true #开启驼峰下划线转换
    lazy-loading-enabled: true #开启懒加载
    aggressive-lazy-loading: false #关闭按需加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台打印sql
    localCacheScope: statement #取消一级缓存，在有多个会话一级分布式场景会产生脏读现象

snow:
  dataCenterId: 12
  machineId: 24

rocketmq:
  name-server: 39.107.52.125:9876
  producer:
    group: TRAIN_TICKET_ORDER_PRODUCER
  consumer:
    group: TRAIN_TICKET_ORDER_CONSUMER